### PR TITLE
Added hires images support

### PR DESCRIPTION
**Pull request by sherakama**
# NOT READY

This PR is to battle:
https://stanfordits.atlassian.net/browse/HSDO-692
https://stanfordits.atlassian.net/browse/HSDO-690

Kerri has also voiced concerns over lossy looking images. 

This PR uses the contrib module: https://www.drupal.org/project/hires_images

TLDR approach of the above module. Set the image style to 2x the needed size and the contrib module will scale down the image to the correct size on the output using the img tags height and width properties.

In order for this module to work with image insert and the wysiwyg the height and width property will have to be added back to the img tag. Right now it is being filtered out. 

The contrib module's approach seems to be an industry option:
* https://code.tutsplus.com/tutorials/the-right-way-to-retinafy-your-websites--net-31793
* http://www.kylejlarson.com/blog/creating-retina-images-for-your-website/
* http://brianflove.com/2014/08/07/retina-display-images/

Another option would be to create a srcset module:
* http://caniuse.com/#search=srcset 
* https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/

An example Implementation has been put on https://sites.stanford.edu/iranian-studies/

### CODE REVIEW

**Comment by sherakama** [comment]
@tsui1 FYI.

**Comment by tsui1** [comment]
:+1:

**Comment by sherakama** [comment]
@all Please leave comments and questions on this thread.

**Comment by josephgknox** [comment]
This looks (Iranian Studies) and sounds (descriptions above) great! It may also provide us with an opportunity to comb through our image styles, deciding which need to be ~ doubled in size.

Clarification question: is the reason that the height and width property need to be added back to the img tag because the "Hi-Res (x2)" effect added by the module adds dynamic inline styles? Are there risks beyond a user using the Full HTML text format to add custom inline styles?

In either case, I'm of the opinion that the benefit of this fix heavily outweighs the potentially introduced risk (?) of users adding crazy inline styles themselves.

To that point, perhaps we additionally explore removing the "Image Properties" option available upon right-clicking (selecting) an image:

img-properties

The most (only) beneficial things available to a user here are a link field and an alternative text field, both of which a user is able to do elsewhere (via the WYSIWYG link option and the inserted image alt field, respectively). We train users in our workshops to use the aforementioned options for including such things anyway rather than adjusting the image properties settings directly.

**Comment by cjwest** [comment]
TIL:

> be sure to use even numbers in both dimensions to prevent displacement of pixels when the image is being downsampled by the browser.

>  the file name plus @2x appended naming convention is becoming standard after being created by Apple for iOS.

**Comment by sherakama** [comment]
Decisions were made:
1. No change to wysiwyg
2. No changes to styles that are used in the insert images functionality
3. Double everything else.

**Comment by sherakama** [comment]
Closing in favor of a new major version.

**Pull request closed without merging**
