### PR TITLE
Re-export of Feature

### PR DESCRIPTION
**Pull request by jbickar**
@sherakama this is what the re-export of the Feature gets you.

### CODE REVIEW

**Comment by jbickar** [comment]
Here is the issue where they decided not to include this info: https://www.drupal.org/node/2308801

**Comment by jbickar** [comment]
This changed between 2.3 and 2.4.

**Comment by sherakama** [comment]
huh, so this is ok. The thread seems reasonable but the effects are shocking.

**Comment by sherakama** [comment]
Need to test.

**Comment by sherakama** [comment]
Works for me.

**Pull request merged**
