### PR TITLE
Hires

### PR DESCRIPTION
**Pull request by sherakama**
# Status
- READY

# Needed By (Date)
- March 1st

# Urgency
- Low

# Steps to Test

1. Build any product. I tested with JSA.
2. Download and but DO NOT enable the hires_images contrib module
3. Checkout this branch for image_styles
4. Run database updates
5. Validate all image styles are outputted at 2x the original size.

Optional test:

1. Select a live site and clone to local
2. Follow steps 2 -> 5 above

# Affected Projects or Products
- Everything.

# Associated Issues
- https://github.com/SU-SWS/stanford_image_styles/pull/28
- https://stanfordits.atlassian.net/browse/BASIC-2340

### CODE REVIEW

**Comment by sherakama** [comment]
Not sure if we want to flush ALL image styles or not. This might cause significant load on the sites environment if we do it all at once.

**Comment by pookmish** [comment]
Ran steps and these are the styles that do not get the hires effect added:

- Thumbnail (100x100)
- Medium (220x220)
- Large (480x480)
- full-width-banner-short
- large-scaled
- large-square
- med-square
- page-width
- sm-scaled
- sm-square

**Comment by pookmish** [comment]
Line 17 of  stanford_image_styles.module : I suggest changing to prepend with some other string for situations when the image style is 'icon-...'. Font awesome could apply some undesired css. `[class^="icon-"], [class*=" icon-"] {...}`

**Comment by sherakama** [comment]
@pookmish 

Good call on the css class names. I prepended it with "image-style-"
Thanks for the testing. full-width-banner-short was the only one that was missing. The others are not tracked in this or were part of the image insert options.

**Comment by jbickar** [comment]
`Download and but DO NOT enable the hires_images contrib module`: what does this do?

**Comment by jbickar** [comment]
Also, shouldn't "5. Validate all image styles are outputted at 2x the original size" read "Validate all _*-banner_ image styles are output at 2x the original size"?

**Comment by jbickar** [comment]
Oh, it's not just `banner` styles. OK, one down 35 to go. Thanks 🇨🇦.

**Comment by jbickar** [comment]
I verified:
- `9-col-banner`
- `icon-square`

**Comment by sherakama** [comment]
Good To Merge

**Comment by sherakama** [comment]
Rebuild the behat tests to match.

**Pull request merged**
