### PR TITLE
SOE-1414: added Header (Scale 850x400)

### PR DESCRIPTION
**Pull request by cjwest**
This adds the new header image used with JSE Dept Related News block

### CODE REVIEW

**Comment by sherakama** [comment]
Full width banner short is used for the full width banner block. I am extremely hesitant to change this  setting. If you need a new size please add a new size.

**Comment by cjwest** [comment]
We are changing it so that it displays at a higher resolution.
Creating a new view mode/style will require updating all the contexts that use this.

**Comment by sherakama** [comment]
I can only allow this if it is exactly double what was before. 
set it to 3200x1000 and keep the scale and crop.
That way it won't mess with existing sites.

**Comment by tsui1** [comment]
:+1:

**Pull request merged**
